version: '3'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile-sqlserver
    ports:
      - "1434:1433"

  spark-jupyter:
    build:
      context: .
      dockerfile: Dockerfile-Jupyter
    container_name: spark-jupyter
    volumes:
      - ./notebooks:/opt/notebooks
      - spark-logs:/opt/spark/spark-events
    ports:
      - '8888:8888'


volumes:
  spark-logs: