version: '3.1'

services:
  sqlserver:
    container_name: bd-spark
    build:
      context: .
    ports:
      - "1434:1433"

  spark-master:
    container_name: spark-master
    build:
      context: .
      target: pyspark
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
      - ./notebooks:/opt/notebooks
    env_file:
      - .env.spark
    ports:
      - '4040:4040'
      - '9090:8080'
      - '7077:7077'

volumes:
  spark-logs: