FROM mcr.microsoft.com/mssql/server:2019-latest

# Switch to root user for access to apt-get install
USER root

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=bi@123456

RUN apt-get -y update  && \
    apt-get install -y curl && \
    apt-get install -y dos2unix


# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Bundle app source
COPY setup.sql /usr/src/app
COPY import-data.sh /usr/src/app
COPY entrypoint.sh /usr/src/app

# Convert import-data.sh to UNIX format
RUN dos2unix *

# Grant permissions for the import-data script to be executable
RUN chmod +x /usr/src/app/import-data.sh


# Switch back to mssql user and run the entrypoint script
USER mssql
ENTRYPOINT /bin/bash ./entrypoint.sh