CREATE VIEW  VW_PARTICIPANTES_ENEM AS(

SELECT [NU_INSCRICAO]
      ,[NU_ANO]
      ,FE.TP_FAIXA_ETARIA_DESCRICAO AS FAIXA_ETARIA
      ,SE.TP_SEXO_DESCRICAO AS SEXO
      ,EC.TP_ESTADO_CIVIL_DESCRICAO AS ESTADO_CIVIL
      ,RA.TP_COR_RACA_DESCRICAO AS RACA
      ,NA.TP_NACIONALIDADE_DESCRICAO AS NACIONALIDADE
      ,ST.TP_ST_CONCLUSAO_DESCRICAO AS SITUACAO_CONCLUSAO
      ,AC.TP_ANO_CONCLUIU_DESCRICAO AS ANO_CONCLUSAO 
      ,ES.TP_ESCOLA_DESCRICAO AS ESCOLA
      ,EN.TP_ENSINO_DESCRICAO AS ENSINO
      ,TR.TP_TREINEIRO_DESCRICAO AS TREINEIRO
  FROM [Enem].[dbo].[Participantes] P WITH(NOLOCK)
  INNER JOIN DimeFaixaEtaria FE 
  ON P.TP_FAIXA_ETARIA = FE.TP_FAIXA_ETARIA_ID
  INNER JOIN DimeSexo SE 
  ON P.TP_SEXO = SE.TP_SEXO_ID
  INNER JOIN DimeRaca RA
  ON P.TP_COR_RACA = RA.TP_COR_RACA_ID
  INNER JOIN DimeNacionalidade NA
  ON P.TP_NACIONALIDADE = NA.TP_NACIONALIDADE_ID
  INNER JOIN DimeSituacaoConclusao ST
  ON P.TP_ST_CONCLUSAO = ST.TP_ST_CONCLUSAO_ID
  INNER JOIN DimeAnoConclusao AC
  ON P.TP_ANO_CONCLUIU = AC.TP_ANO_CONCLUIU_ID
  INNER JOIN DimeEscola ES
  ON P.TP_ESCOLA = ES.TP_ESCOLA_ID
  INNER JOIN DimeEnsino EN
  ON P.TP_ENSINO = EN.TP_ENSINO_ID
  INNER JOIN DimeTreineiro TR
  ON P.IN_TREINEIRO = TR.TP_TREINEIRO_ID
  INNER JOIN DimeEstadoCivil EC
  ON P.TP_ESTADO_CIVIL = EC.TP_ESTADO_CIVIL_ID
)