name: notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: commits
        SLACK_TITLE: Comunicado:
        SLACK_USERNAME: BotLeonardo
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "Uma nova atualização foi adicionada na Branch main."
